# Generated by Django 3.1.5 on 2021-01-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.FloatField()),
                ('saldo_final', models.FloatField()),
                ('mensagem', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrato', to='usuario.usuario')),
            ],
        ),
    ]
